[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
monitor_speed = 115200

[env:native]
platform = native
build_flags = -DUNIT_TEST
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
test_framework = unity
